[settings]
debug = true

[whisper]
host = "localhost"
port = 8081

[whisper.backend]
executable = "whisper.cpp/server"
model = "whisper.cpp/models/ggml-base.en.bin"


[ollama]
host = "localhost"
port = 8082

[ollama.frontend]
chat_model = "mistral:v0.2"
embed_model = "mxbai-embed-large"

[ollama.backend]
executable = "/usr/local/bin/ollama"
