[settings]
debug = false
regenerate_embeddings = false

[api]
host = "localhost"
port = 8000

[database]
uri = "sqlite:///./test.db"

[chromadb]
host = "localhost"
port = 8001

[whisper]
host = "localhost"
port = 8002
executable = "whisper.cpp/server"
model = "whisper.cpp/models/ggml-base.en.bin"

[ollama]
host = "localhost"
port = 8003
executable = "/usr/local/bin/ollama"
chat_model = "llama3"
embed_model = "mxbai-embed-large"
