[settings]
debug = false
regenerate_embeddings = false

[api]
host = "172.17.0.2"
port = 8000
media_path = "./media"

[database]
uri = "sqlite:///./test.db"

[chromadb]
host = "localhost"
port = 8001
external = false

[whisper]
host = "localhost"
port = 8002
external = false
executable = "whisper.cpp/server"
model = "whisper.cpp/models/ggml-base.en.bin"

[ollama]
host = "host.docker.internal"
port = 8003
external = true
executable = "/usr/local/bin/ollama"
chat_model = "llama3"
embed_model = "mxbai-embed-large"
